NO_VER option on build scripts, no version bump
Run like this:

    NO_VER=true bin/ios
    NO_VER=true bin/android

To skip bumping the version number.  Useful for testing builds in dev so
production builds won't appear to skip versions.

diff --git a/bin/android b/bin/android
--- a/bin/android
+++ b/bin/android
@@ -81,16 +81,18 @@ done
 rm -f $ANDROID_PROJECT_DIR/res/drawable/{icon.png,screen.png}
 cp $CORDOVA_DIR/res/android/icons/wmatic_icon.png $ANDROID_PROJECT_DIR/res/drawable
 
-
-msg "Updating app version to: $APP_VERSION"
-sed -i '.bak' "s/android-versionCode=\"[0-9]*\"/android-versionCode=\"$APP_VERSION\"/" $CORDOVA_DIR/config.xml
-if [ "$?" -ne 0 ]; then
- echo "Could not update app version, bailing"
- exit 1
+if [ "$NO_VER" ]; then
+  msg "NO_VER was set, will not increment the build version"
+else
+  msg "Updating app version to: $APP_VERSION"
+  sed -i '.bak' "s/android-versionCode=\"[0-9]*\"/android-versionCode=\"$APP_VERSION\"/" $CORDOVA_DIR/config.xml
+  if [ "$?" -ne 0 ]; then
+   echo "Could not update app version, bailing"
+   exit 1
+  fi
+  rm $CORDOVA_DIR/config.xml.bak
+  echo $APP_VERSION > $CORDOVA_DIR/android-last-build-version
 fi
-rm $CORDOVA_DIR/config.xml.bak
-echo $APP_VERSION > $CORDOVA_DIR/android-last-build-version
-
 
 msg "Building android cordova project and .apk"
 MOBILE_PLATFORM=android ember cordova:build --environment=${EMBER_ENV:=production} --platform=android
diff --git a/bin/ios b/bin/ios
--- a/bin/ios
+++ b/bin/ios
@@ -26,19 +26,23 @@ ember cordova platform add ios
 msg "Adding plugins"
 source  $DIR/install_plugins
 
-PREV_VERSION=$(cat $CORDOVA_DIR/ios-last-build-version)
-PREFIX=$(echo "$PREV_VERSION" | grep -o "[0-9]*\.[0-9]*\.")
-LAST_NODE=$(echo "$PREV_VERSION" | grep -o "[0-9]*$")
-NEW_VERSION="$PREFIX$(($LAST_NODE+1))"
+if [ "$NO_VER" ]; then
+  msg "NO_VER was set, will not increment the build version"
+else
+  PREV_VERSION=$(cat $CORDOVA_DIR/ios-last-build-version)
+  PREFIX=$(echo "$PREV_VERSION" | grep -o "[0-9]*\.[0-9]*\.")
+  LAST_NODE=$(echo "$PREV_VERSION" | grep -o "[0-9]*$")
+  NEW_VERSION="$PREFIX$(($LAST_NODE+1))"
 
-msg "Updating version to: $NEW_VERSION"
-sed -i '.bak' "s/ios-CFBundleVersion=\"[0-9]*\.[0-9]*\.[0-9]*\"/ios-CFBundleVersion=\"$NEW_VERSION\"/" $CORDOVA_DIR/config.xml
-if [ "$?" -ne 0 ]; then
-  echo "Could not update version, bailing"
-  exit 1
+  msg "Updating version to: $NEW_VERSION"
+  sed -i '.bak' "s/ios-CFBundleVersion=\"[0-9]*\.[0-9]*\.[0-9]*\"/ios-CFBundleVersion=\"$NEW_VERSION\"/" $CORDOVA_DIR/config.xml
+  if [ "$?" -ne 0 ]; then
+    echo "Could not update version, bailing"
+    exit 1
+  fi
+  rm $CORDOVA_DIR/config.xml.bak
+  echo $NEW_VERSION > $CORDOVA_DIR/ios-last-build-version
 fi
-rm $CORDOVA_DIR/config.xml.bak
-echo $NEW_VERSION > $CORDOVA_DIR/ios-last-build-version
 
 msg "Building XCode project"
 MOBILE_PLATFORM=ios ember cordova:build --environment ${EMBER_ENV:=production} --platform ios
